/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Nov 30, 2015
 *			root <root@cyclone5>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"		   HDF5 Version: 1.8.16\n"
	"		  Configured on: Mon Nov 30 02:44:24 UTC 2015\n"
	"		  Configured by: norxander@debian\n"
	"		 Configure mode: production\n"
	"		    Host system: arm-poky-linux-gnueabi\n"
	"	      Uname information: Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux\n"
	"		       Byte sex: little-endian\n"
	"		      Libraries: static, shared\n"
	"	     Installation point: /media/dataLinux/Work/Git/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/hdf5/1.8.16-r0/image/usr\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: production\n"
	"                     C Compiler: /media/dataLinux/Work/Git/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc  -march=armv7-a -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/media/dataLinux/Work/Git/build/tmp/sysroots/cyclone5\n"
	"                         CFLAGS:  -O2 -pipe -g -feliminate-unused-debug-types\n"
	"                      H5_CFLAGS:  \n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API\n"
	"                    AM_CPPFLAGS: -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/media/dataLinux/Work/Git/build/tmp/sysroots/cyclone5/usr/include\n"
	"               Shared C Library: yes\n"
	"               Static C Library: yes\n"
	"  Statically Linked Executables: no\n"
	"                        LDFLAGS: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed\n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS:  -L/media/dataLinux/Work/Git/build/tmp/sysroots/cyclone5/usr/lib\n"
	" 	 	Extra libraries: -lz -ldl -lm \n"
	" 		       Archiver: arm-poky-linux-gnueabi-ar\n"
	" 		 	 Ranlib: arm-poky-linux-gnueabi-ranlib\n"
	" 	      Debugged Packages: \n"
	"		    API Tracing: no\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: yes\n"
	"                   C++ Compiler: /media/dataLinux/Work/Git/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++  -march=armv7-a -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/media/dataLinux/Work/Git/build/tmp/sysroots/cyclone5\n"
	"                      C++ Flags:  -O2 -pipe -g -feliminate-unused-debug-types -fvisibility-inlines-hidden\n"
	"                   H5 C++ Flags:  \n"
	"                   AM C++ Flags: \n"
	"             Shared C++ Library: yes\n"
	"             Static C++ Library: yes\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: no\n"
	"             High Level library: yes\n"
	"                   Threadsafety: no\n"
	"            Default API Mapping: v18\n"
	" With Deprecated Public Symbols: yes\n"
	"         I/O filters (external): deflate(zlib)\n"
	"                            MPE: no\n"
	"                     Direct VFD: no\n"
	"                        dmalloc: no\n"
	"Clear file buffers before write: yes\n"
	"           Using memory checker: no\n"
	"         Function Stack Tracing: no\n"
	"      Strict File Format Checks: no\n"
	"   Optimization Instrumentation: no\n"
;

